// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Volo.Abp.Domain.Entities;

namespace BookStore.Domain.Models;

public partial class OrderDetail : Entity
{
    public int OrderId { get; set; }

    public int ProductId { get; set; }

    public double UnitPrice { get; set; }

    public short Quantity { get; set; }

    public double Discount { get; set; }

    public virtual Order Order { get; set; }

    public virtual Product Product { get; set; }

    public override object[] GetKeys()
    {
        return new object[] { OrderId, ProductId };
    }
}